kind: pipeline
type: docker
name: default


#git 仓库
gitInfo:
  ghost: &gitInfo.host 10.4.7.100
  gusername: &gitInfo.username root
  gpassword: &gitInfo.password 123456
  gport: &gitInfo.port 22
  giturl: &gitInfo.giturl git clone ssh://git@10.4.7.100:10022/jettjia/goods-srv-grpc-test.git
  srvPath: &gitInfo.srvPath goods-srv-grpc-test

#docker
dockerInfo:
  image: &dockerInfo.image my-go-micro
  tag : &dockerInfo.tag latest
  dport: &dockerInfo.port 50051

#harbor仓库
harborInfo:
  hhost: &harborInfo.host 10.4.7.100
  husername: &harborInfo.username root
  hpassword: &harborInfo.password 123456
  hport: &harborInfo.hport 22
  repoAddr: &harborInfo.repoAddr 10.4.7.100:85
  repoPath: &harborInfo.repoPath 10.4.7.100:85/test
  harborUser: &harborInfo.harborUser admin
  harborPass: &harborInfo.harborPass Harbor12345

# dev服务器
dev1:
  d1host: &dev1.host 10.4.7.71

# master服务器
master1:
  m1host: &master1.host 10.4.7.102

clone:
  disable: true

steps:
  - name: clone
    pull: if-not-exists
    image: appleboy/drone-ssh
    settings:
      host: *gitInfo.host
      username: *gitInfo.username
      password: *gitInfo.password
      port: *gitInfo.port
      script:
        - cd /drone/src
        - *gitInfo.giturl
        - cd goods-srv-grpc-test
        - git checkout master
        - chmod -R 777 ./*

  - name: build-image
    pull: if-not-exists
    image: appleboy/drone-ssh
    settings:
      host: 10.4.7.100
      username: root
      password: 123456
      port: 22
      script:
        - cd /drone/src/goods-srv-grpc-test
        - docker build -t my-go-micro .
        - docker tag my-go-micro 10.4.7.100:85/test/my-go-micro:latest
        - docker login -u admin -p Harbor12345 10.4.7.100:85
        - docker push 10.4.7.100:85/test/my-go-micro:latest

        - docker rmi my-go-micro
        - docker rmi 10.4.7.100:85/test/my-go-micro:latest

  # 发布 dev环境
  - name: deploy-dev
    pull: if-not-exists
    image: appleboy/drone-ssh
    settings:
      host: 10.4.7.71
      username: root
      password: 123456
      port: 22
      script:
        - docker login -u admin -p Harbor12345 10.4.7.100:85
        - docker pull 10.4.7.100:85/test/my-go-micro:latest
        - list=$(docker ps -a | grep goods-srv | awk '{print $1}')
        - test "$list" = "" && echo "none my-go-micro containers running" || docker stop $list
        - docker rm $list
        - docker run -p 50051:50051 -d -v /data/my-go-micro:/apps/tmp 10.4.7.100:85/test/my-go-micro:latest
    when:
      event: [ push, pull_request ]
      branch: [ dev ]

  # 发布 master环境
  - name: deploy-prod
    pull: if-not-exists
    image: appleboy/drone-ssh
    settings:
      host: 10.4.7.102
      username: root
      password: 123456
      port: 22
      script:
        - docker login -u admin -p Harbor12345 10.4.7.100:85
        - docker pull 10.4.7.100:85/test/my-go-micro:latest
        - list=$(docker ps -a | grep goods-srv | awk '{print $1}')
        - test "$list" = "" && echo "none my-go-micro containers running" || docker stop $list
        - docker rm $list
        - docker run -p 50051:50051 -d -v /data/my-go-micro:/apps/tmp 10.4.7.100:85/test/my-go-micro:latest
    when:
      event: [ push, pull_request ]
      branch: [ master ]


volumes:
  - name: sshkeys
    host:
      path: /root/.ssh

  - name: dockerdaemon
    host:
      path: /etc/docker/daemon.json